import Head from "next/head";
import Router from "next/router";
import { useState } from "react";
import listuser from "../components/userlist.json";

export default function Home() {
  const [user, setuser] = useState({ username: "", password: "" });
  const submithandler = (e) => {
    setuser({ ...user, [e.target.name]: e.target.value });
  };

  const checkuser = () => {
    if (user.username && user.password) {
      const liuser = listuser.users.filter(
        (a) => user.username === a.username && user.password === a.password
      );
      if (liuser.length) {
        Router.push("/listadd");
      } else {
        alert("username or password incorrect");
      }
    } else {
      alert("all field required");
    }
  };

  return (
    <div>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="login-body">
        <div className="login-content">
          <div className="login-border">
            <header>
              <h1 className="gradient-text">login</h1>
            </header>
            <input
              name="username"
              type="text"
              placeholder="username"
              value={user.username}
              onChange={submithandler}
            />
            <input
              name="password"
              type="password"
              placeholder="password"
              value={user.password}
              onChange={submithandler}
            />
            <input type="button" value="login" onClick={checkuser} />
          </div>
        </div>
      </div>
    </div>
  );
}
